version: '3.7'

services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        build: ./docker/php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ../xivapi:/var/www/xivapi:cached
            - ./docker/logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ../xivapi:/var/www/symfony:cached
            - ./docker/logs/nginx:/var/log/nginx:cached
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: dalamud
          MYSQL_USER: dalamud
          MYSQL_PASSWORD: dalamud
          MYSQL_DATABASE: dalamud

    redis:
        image: redis

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        container_name: dalamud
        environment:
          - node.name=dalamud
          - cluster.initial_master_nodes=dalamud
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - esdata01:/usr/share/elasticsearch/data:delegated
        ports:
          - 9200:9200
        networks:
          - esnet

    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash:cached
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./docker/logs/symfony:/var/www/symfony/var/log:cached
            - ./docker/logs/nginx:/var/log/nginx:cached

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
